 
[G, A, q, rock] = getTestCase('dims', [60 60], ...
                            'grid', 'cart',...
                            'twistval', 0.01, ...
                            'perm', 'tarbert', ...
                            'layers', 3, ...
                            'stencil',  'tpfa', ...
                            'flow',   'bc', ...
                            'griddims',  [], ...
                            'ordering', 'default', ...
                            'gridaspect', [2 1]);

%%

solver = @(q, varargin) solveMultigrid(G, A, q,...
                        'coarsening', 'standard', ...
                        'verbose', false, ...
                        'iterations', 1, ...
                        'interpolator', 'standard', varargin{:});
tic
[x, res, meta, partitions] =  solver(q, 'doSolve', false);
toc

preconditioner = @(q) solver(q, 'partitions', partitions);
%%
preconditioner = makeMultigridPreconditioner(G, A, q,...
                        'coarsening', 'standard', ...
                        'verbose', false, ...
                        'iterations', 1, ...
                        'interpolator', 'standard');

%%

[x,flag,relres,iter,resvec] = gmres(A, q, [], 1e-6, 100, preconditioner);
%%
[x,flag,relres,iter,resvec] = bicg(A, q, 1e-6, 100, preconditioner);
